repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]